/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChaptersUseStateRouteImport } from './routes/chapters/use-state'
import { Route as ChaptersUseRefRouteImport } from './routes/chapters/use-ref'
import { Route as ChaptersUseReducerRouteImport } from './routes/chapters/use-reducer'
import { Route as ChaptersUseEffectRouteImport } from './routes/chapters/use-effect'
import { Route as ChaptersStateStructureRouteImport } from './routes/chapters/state-structure'
import { Route as ChaptersSharingStateRouteImport } from './routes/chapters/sharing-state'
import { Route as ChaptersReactiveInputRouteImport } from './routes/chapters/reactive-input'
import { Route as ChaptersMemoizationRouteImport } from './routes/chapters/memoization'
import { Route as ChaptersListsKeysRouteImport } from './routes/chapters/lists-keys'
import { Route as ChaptersJsxRouteImport } from './routes/chapters/jsx'
import { Route as ChaptersFormsRouteImport } from './routes/chapters/forms'
import { Route as ChaptersEventsRouteImport } from './routes/chapters/events'
import { Route as ChaptersErrorBoundariesRouteImport } from './routes/chapters/error-boundaries'
import { Route as ChaptersCustomHooksRouteImport } from './routes/chapters/custom-hooks'
import { Route as ChaptersContextRouteImport } from './routes/chapters/context'
import { Route as ChaptersConditionalRenderingRouteImport } from './routes/chapters/conditional-rendering'
import { Route as ChaptersComponentsPropsRouteImport } from './routes/chapters/components-props'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersUseStateRoute = ChaptersUseStateRouteImport.update({
  id: '/chapters/use-state',
  path: '/chapters/use-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersUseRefRoute = ChaptersUseRefRouteImport.update({
  id: '/chapters/use-ref',
  path: '/chapters/use-ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersUseReducerRoute = ChaptersUseReducerRouteImport.update({
  id: '/chapters/use-reducer',
  path: '/chapters/use-reducer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersUseEffectRoute = ChaptersUseEffectRouteImport.update({
  id: '/chapters/use-effect',
  path: '/chapters/use-effect',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersStateStructureRoute = ChaptersStateStructureRouteImport.update({
  id: '/chapters/state-structure',
  path: '/chapters/state-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSharingStateRoute = ChaptersSharingStateRouteImport.update({
  id: '/chapters/sharing-state',
  path: '/chapters/sharing-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersReactiveInputRoute = ChaptersReactiveInputRouteImport.update({
  id: '/chapters/reactive-input',
  path: '/chapters/reactive-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersMemoizationRoute = ChaptersMemoizationRouteImport.update({
  id: '/chapters/memoization',
  path: '/chapters/memoization',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersListsKeysRoute = ChaptersListsKeysRouteImport.update({
  id: '/chapters/lists-keys',
  path: '/chapters/lists-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersJsxRoute = ChaptersJsxRouteImport.update({
  id: '/chapters/jsx',
  path: '/chapters/jsx',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersFormsRoute = ChaptersFormsRouteImport.update({
  id: '/chapters/forms',
  path: '/chapters/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersEventsRoute = ChaptersEventsRouteImport.update({
  id: '/chapters/events',
  path: '/chapters/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersErrorBoundariesRoute = ChaptersErrorBoundariesRouteImport.update({
  id: '/chapters/error-boundaries',
  path: '/chapters/error-boundaries',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersCustomHooksRoute = ChaptersCustomHooksRouteImport.update({
  id: '/chapters/custom-hooks',
  path: '/chapters/custom-hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersContextRoute = ChaptersContextRouteImport.update({
  id: '/chapters/context',
  path: '/chapters/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersConditionalRenderingRoute =
  ChaptersConditionalRenderingRouteImport.update({
    id: '/chapters/conditional-rendering',
    path: '/chapters/conditional-rendering',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChaptersComponentsPropsRoute = ChaptersComponentsPropsRouteImport.update({
  id: '/chapters/components-props',
  path: '/chapters/components-props',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chapters/components-props': typeof ChaptersComponentsPropsRoute
  '/chapters/conditional-rendering': typeof ChaptersConditionalRenderingRoute
  '/chapters/context': typeof ChaptersContextRoute
  '/chapters/custom-hooks': typeof ChaptersCustomHooksRoute
  '/chapters/error-boundaries': typeof ChaptersErrorBoundariesRoute
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/forms': typeof ChaptersFormsRoute
  '/chapters/jsx': typeof ChaptersJsxRoute
  '/chapters/lists-keys': typeof ChaptersListsKeysRoute
  '/chapters/memoization': typeof ChaptersMemoizationRoute
  '/chapters/reactive-input': typeof ChaptersReactiveInputRoute
  '/chapters/sharing-state': typeof ChaptersSharingStateRoute
  '/chapters/state-structure': typeof ChaptersStateStructureRoute
  '/chapters/use-effect': typeof ChaptersUseEffectRoute
  '/chapters/use-reducer': typeof ChaptersUseReducerRoute
  '/chapters/use-ref': typeof ChaptersUseRefRoute
  '/chapters/use-state': typeof ChaptersUseStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chapters/components-props': typeof ChaptersComponentsPropsRoute
  '/chapters/conditional-rendering': typeof ChaptersConditionalRenderingRoute
  '/chapters/context': typeof ChaptersContextRoute
  '/chapters/custom-hooks': typeof ChaptersCustomHooksRoute
  '/chapters/error-boundaries': typeof ChaptersErrorBoundariesRoute
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/forms': typeof ChaptersFormsRoute
  '/chapters/jsx': typeof ChaptersJsxRoute
  '/chapters/lists-keys': typeof ChaptersListsKeysRoute
  '/chapters/memoization': typeof ChaptersMemoizationRoute
  '/chapters/reactive-input': typeof ChaptersReactiveInputRoute
  '/chapters/sharing-state': typeof ChaptersSharingStateRoute
  '/chapters/state-structure': typeof ChaptersStateStructureRoute
  '/chapters/use-effect': typeof ChaptersUseEffectRoute
  '/chapters/use-reducer': typeof ChaptersUseReducerRoute
  '/chapters/use-ref': typeof ChaptersUseRefRoute
  '/chapters/use-state': typeof ChaptersUseStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chapters/components-props': typeof ChaptersComponentsPropsRoute
  '/chapters/conditional-rendering': typeof ChaptersConditionalRenderingRoute
  '/chapters/context': typeof ChaptersContextRoute
  '/chapters/custom-hooks': typeof ChaptersCustomHooksRoute
  '/chapters/error-boundaries': typeof ChaptersErrorBoundariesRoute
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/forms': typeof ChaptersFormsRoute
  '/chapters/jsx': typeof ChaptersJsxRoute
  '/chapters/lists-keys': typeof ChaptersListsKeysRoute
  '/chapters/memoization': typeof ChaptersMemoizationRoute
  '/chapters/reactive-input': typeof ChaptersReactiveInputRoute
  '/chapters/sharing-state': typeof ChaptersSharingStateRoute
  '/chapters/state-structure': typeof ChaptersStateStructureRoute
  '/chapters/use-effect': typeof ChaptersUseEffectRoute
  '/chapters/use-reducer': typeof ChaptersUseReducerRoute
  '/chapters/use-ref': typeof ChaptersUseRefRoute
  '/chapters/use-state': typeof ChaptersUseStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chapters/components-props'
    | '/chapters/conditional-rendering'
    | '/chapters/context'
    | '/chapters/custom-hooks'
    | '/chapters/error-boundaries'
    | '/chapters/events'
    | '/chapters/forms'
    | '/chapters/jsx'
    | '/chapters/lists-keys'
    | '/chapters/memoization'
    | '/chapters/reactive-input'
    | '/chapters/sharing-state'
    | '/chapters/state-structure'
    | '/chapters/use-effect'
    | '/chapters/use-reducer'
    | '/chapters/use-ref'
    | '/chapters/use-state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chapters/components-props'
    | '/chapters/conditional-rendering'
    | '/chapters/context'
    | '/chapters/custom-hooks'
    | '/chapters/error-boundaries'
    | '/chapters/events'
    | '/chapters/forms'
    | '/chapters/jsx'
    | '/chapters/lists-keys'
    | '/chapters/memoization'
    | '/chapters/reactive-input'
    | '/chapters/sharing-state'
    | '/chapters/state-structure'
    | '/chapters/use-effect'
    | '/chapters/use-reducer'
    | '/chapters/use-ref'
    | '/chapters/use-state'
  id:
    | '__root__'
    | '/'
    | '/chapters/components-props'
    | '/chapters/conditional-rendering'
    | '/chapters/context'
    | '/chapters/custom-hooks'
    | '/chapters/error-boundaries'
    | '/chapters/events'
    | '/chapters/forms'
    | '/chapters/jsx'
    | '/chapters/lists-keys'
    | '/chapters/memoization'
    | '/chapters/reactive-input'
    | '/chapters/sharing-state'
    | '/chapters/state-structure'
    | '/chapters/use-effect'
    | '/chapters/use-reducer'
    | '/chapters/use-ref'
    | '/chapters/use-state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChaptersComponentsPropsRoute: typeof ChaptersComponentsPropsRoute
  ChaptersConditionalRenderingRoute: typeof ChaptersConditionalRenderingRoute
  ChaptersContextRoute: typeof ChaptersContextRoute
  ChaptersCustomHooksRoute: typeof ChaptersCustomHooksRoute
  ChaptersErrorBoundariesRoute: typeof ChaptersErrorBoundariesRoute
  ChaptersEventsRoute: typeof ChaptersEventsRoute
  ChaptersFormsRoute: typeof ChaptersFormsRoute
  ChaptersJsxRoute: typeof ChaptersJsxRoute
  ChaptersListsKeysRoute: typeof ChaptersListsKeysRoute
  ChaptersMemoizationRoute: typeof ChaptersMemoizationRoute
  ChaptersReactiveInputRoute: typeof ChaptersReactiveInputRoute
  ChaptersSharingStateRoute: typeof ChaptersSharingStateRoute
  ChaptersStateStructureRoute: typeof ChaptersStateStructureRoute
  ChaptersUseEffectRoute: typeof ChaptersUseEffectRoute
  ChaptersUseReducerRoute: typeof ChaptersUseReducerRoute
  ChaptersUseRefRoute: typeof ChaptersUseRefRoute
  ChaptersUseStateRoute: typeof ChaptersUseStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/use-state': {
      id: '/chapters/use-state'
      path: '/chapters/use-state'
      fullPath: '/chapters/use-state'
      preLoaderRoute: typeof ChaptersUseStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/use-ref': {
      id: '/chapters/use-ref'
      path: '/chapters/use-ref'
      fullPath: '/chapters/use-ref'
      preLoaderRoute: typeof ChaptersUseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/use-reducer': {
      id: '/chapters/use-reducer'
      path: '/chapters/use-reducer'
      fullPath: '/chapters/use-reducer'
      preLoaderRoute: typeof ChaptersUseReducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/use-effect': {
      id: '/chapters/use-effect'
      path: '/chapters/use-effect'
      fullPath: '/chapters/use-effect'
      preLoaderRoute: typeof ChaptersUseEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/state-structure': {
      id: '/chapters/state-structure'
      path: '/chapters/state-structure'
      fullPath: '/chapters/state-structure'
      preLoaderRoute: typeof ChaptersStateStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/sharing-state': {
      id: '/chapters/sharing-state'
      path: '/chapters/sharing-state'
      fullPath: '/chapters/sharing-state'
      preLoaderRoute: typeof ChaptersSharingStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/reactive-input': {
      id: '/chapters/reactive-input'
      path: '/chapters/reactive-input'
      fullPath: '/chapters/reactive-input'
      preLoaderRoute: typeof ChaptersReactiveInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/memoization': {
      id: '/chapters/memoization'
      path: '/chapters/memoization'
      fullPath: '/chapters/memoization'
      preLoaderRoute: typeof ChaptersMemoizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/lists-keys': {
      id: '/chapters/lists-keys'
      path: '/chapters/lists-keys'
      fullPath: '/chapters/lists-keys'
      preLoaderRoute: typeof ChaptersListsKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/jsx': {
      id: '/chapters/jsx'
      path: '/chapters/jsx'
      fullPath: '/chapters/jsx'
      preLoaderRoute: typeof ChaptersJsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/forms': {
      id: '/chapters/forms'
      path: '/chapters/forms'
      fullPath: '/chapters/forms'
      preLoaderRoute: typeof ChaptersFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/events': {
      id: '/chapters/events'
      path: '/chapters/events'
      fullPath: '/chapters/events'
      preLoaderRoute: typeof ChaptersEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/error-boundaries': {
      id: '/chapters/error-boundaries'
      path: '/chapters/error-boundaries'
      fullPath: '/chapters/error-boundaries'
      preLoaderRoute: typeof ChaptersErrorBoundariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/custom-hooks': {
      id: '/chapters/custom-hooks'
      path: '/chapters/custom-hooks'
      fullPath: '/chapters/custom-hooks'
      preLoaderRoute: typeof ChaptersCustomHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/context': {
      id: '/chapters/context'
      path: '/chapters/context'
      fullPath: '/chapters/context'
      preLoaderRoute: typeof ChaptersContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/conditional-rendering': {
      id: '/chapters/conditional-rendering'
      path: '/chapters/conditional-rendering'
      fullPath: '/chapters/conditional-rendering'
      preLoaderRoute: typeof ChaptersConditionalRenderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/components-props': {
      id: '/chapters/components-props'
      path: '/chapters/components-props'
      fullPath: '/chapters/components-props'
      preLoaderRoute: typeof ChaptersComponentsPropsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChaptersComponentsPropsRoute: ChaptersComponentsPropsRoute,
  ChaptersConditionalRenderingRoute: ChaptersConditionalRenderingRoute,
  ChaptersContextRoute: ChaptersContextRoute,
  ChaptersCustomHooksRoute: ChaptersCustomHooksRoute,
  ChaptersErrorBoundariesRoute: ChaptersErrorBoundariesRoute,
  ChaptersEventsRoute: ChaptersEventsRoute,
  ChaptersFormsRoute: ChaptersFormsRoute,
  ChaptersJsxRoute: ChaptersJsxRoute,
  ChaptersListsKeysRoute: ChaptersListsKeysRoute,
  ChaptersMemoizationRoute: ChaptersMemoizationRoute,
  ChaptersReactiveInputRoute: ChaptersReactiveInputRoute,
  ChaptersSharingStateRoute: ChaptersSharingStateRoute,
  ChaptersStateStructureRoute: ChaptersStateStructureRoute,
  ChaptersUseEffectRoute: ChaptersUseEffectRoute,
  ChaptersUseReducerRoute: ChaptersUseReducerRoute,
  ChaptersUseRefRoute: ChaptersUseRefRoute,
  ChaptersUseStateRoute: ChaptersUseStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
