/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChaptersUseStateRouteImport } from './routes/chapters/use-state'
import { Route as ChaptersUseRefRouteImport } from './routes/chapters/use-ref'
import { Route as ChaptersUseReducerRouteImport } from './routes/chapters/use-reducer'
import { Route as ChaptersUseEffectRouteImport } from './routes/chapters/use-effect'
import { Route as ChaptersReactRenderingRouteImport } from './routes/chapters/react-rendering'
import { Route as ChaptersMoveStateDownRouteImport } from './routes/chapters/move-state-down'
import { Route as ChaptersMemoizationRouteImport } from './routes/chapters/memoization'
import { Route as ChaptersListsKeysRouteImport } from './routes/chapters/lists-keys'
import { Route as ChaptersLiftContentUpRouteImport } from './routes/chapters/lift-content-up'
import { Route as ChaptersJsxRouteImport } from './routes/chapters/jsx'
import { Route as ChaptersFormsRouteImport } from './routes/chapters/forms'
import { Route as ChaptersEventsRouteImport } from './routes/chapters/events'
import { Route as ChaptersDontCallFunctionComponentsRouteImport } from './routes/chapters/dont-call-function-components'
import { Route as ChaptersCustomHooksRouteImport } from './routes/chapters/custom-hooks'
import { Route as ChaptersContextRouteImport } from './routes/chapters/context'
import { Route as ChaptersConditionalRenderingRouteImport } from './routes/chapters/conditional-rendering'
import { Route as ChaptersComponentsPropsRouteImport } from './routes/chapters/components-props'
import { Route as ChaptersComponentDesignRouteImport } from './routes/chapters/component-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersUseStateRoute = ChaptersUseStateRouteImport.update({
  id: '/chapters/use-state',
  path: '/chapters/use-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersUseRefRoute = ChaptersUseRefRouteImport.update({
  id: '/chapters/use-ref',
  path: '/chapters/use-ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersUseReducerRoute = ChaptersUseReducerRouteImport.update({
  id: '/chapters/use-reducer',
  path: '/chapters/use-reducer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersUseEffectRoute = ChaptersUseEffectRouteImport.update({
  id: '/chapters/use-effect',
  path: '/chapters/use-effect',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersReactRenderingRoute = ChaptersReactRenderingRouteImport.update({
  id: '/chapters/react-rendering',
  path: '/chapters/react-rendering',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersMoveStateDownRoute = ChaptersMoveStateDownRouteImport.update({
  id: '/chapters/move-state-down',
  path: '/chapters/move-state-down',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersMemoizationRoute = ChaptersMemoizationRouteImport.update({
  id: '/chapters/memoization',
  path: '/chapters/memoization',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersListsKeysRoute = ChaptersListsKeysRouteImport.update({
  id: '/chapters/lists-keys',
  path: '/chapters/lists-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersLiftContentUpRoute = ChaptersLiftContentUpRouteImport.update({
  id: '/chapters/lift-content-up',
  path: '/chapters/lift-content-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersJsxRoute = ChaptersJsxRouteImport.update({
  id: '/chapters/jsx',
  path: '/chapters/jsx',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersFormsRoute = ChaptersFormsRouteImport.update({
  id: '/chapters/forms',
  path: '/chapters/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersEventsRoute = ChaptersEventsRouteImport.update({
  id: '/chapters/events',
  path: '/chapters/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersDontCallFunctionComponentsRoute =
  ChaptersDontCallFunctionComponentsRouteImport.update({
    id: '/chapters/dont-call-function-components',
    path: '/chapters/dont-call-function-components',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChaptersCustomHooksRoute = ChaptersCustomHooksRouteImport.update({
  id: '/chapters/custom-hooks',
  path: '/chapters/custom-hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersContextRoute = ChaptersContextRouteImport.update({
  id: '/chapters/context',
  path: '/chapters/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersConditionalRenderingRoute =
  ChaptersConditionalRenderingRouteImport.update({
    id: '/chapters/conditional-rendering',
    path: '/chapters/conditional-rendering',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChaptersComponentsPropsRoute = ChaptersComponentsPropsRouteImport.update({
  id: '/chapters/components-props',
  path: '/chapters/components-props',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersComponentDesignRoute = ChaptersComponentDesignRouteImport.update({
  id: '/chapters/component-design',
  path: '/chapters/component-design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chapters/component-design': typeof ChaptersComponentDesignRoute
  '/chapters/components-props': typeof ChaptersComponentsPropsRoute
  '/chapters/conditional-rendering': typeof ChaptersConditionalRenderingRoute
  '/chapters/context': typeof ChaptersContextRoute
  '/chapters/custom-hooks': typeof ChaptersCustomHooksRoute
  '/chapters/dont-call-function-components': typeof ChaptersDontCallFunctionComponentsRoute
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/forms': typeof ChaptersFormsRoute
  '/chapters/jsx': typeof ChaptersJsxRoute
  '/chapters/lift-content-up': typeof ChaptersLiftContentUpRoute
  '/chapters/lists-keys': typeof ChaptersListsKeysRoute
  '/chapters/memoization': typeof ChaptersMemoizationRoute
  '/chapters/move-state-down': typeof ChaptersMoveStateDownRoute
  '/chapters/react-rendering': typeof ChaptersReactRenderingRoute
  '/chapters/use-effect': typeof ChaptersUseEffectRoute
  '/chapters/use-reducer': typeof ChaptersUseReducerRoute
  '/chapters/use-ref': typeof ChaptersUseRefRoute
  '/chapters/use-state': typeof ChaptersUseStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chapters/component-design': typeof ChaptersComponentDesignRoute
  '/chapters/components-props': typeof ChaptersComponentsPropsRoute
  '/chapters/conditional-rendering': typeof ChaptersConditionalRenderingRoute
  '/chapters/context': typeof ChaptersContextRoute
  '/chapters/custom-hooks': typeof ChaptersCustomHooksRoute
  '/chapters/dont-call-function-components': typeof ChaptersDontCallFunctionComponentsRoute
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/forms': typeof ChaptersFormsRoute
  '/chapters/jsx': typeof ChaptersJsxRoute
  '/chapters/lift-content-up': typeof ChaptersLiftContentUpRoute
  '/chapters/lists-keys': typeof ChaptersListsKeysRoute
  '/chapters/memoization': typeof ChaptersMemoizationRoute
  '/chapters/move-state-down': typeof ChaptersMoveStateDownRoute
  '/chapters/react-rendering': typeof ChaptersReactRenderingRoute
  '/chapters/use-effect': typeof ChaptersUseEffectRoute
  '/chapters/use-reducer': typeof ChaptersUseReducerRoute
  '/chapters/use-ref': typeof ChaptersUseRefRoute
  '/chapters/use-state': typeof ChaptersUseStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chapters/component-design': typeof ChaptersComponentDesignRoute
  '/chapters/components-props': typeof ChaptersComponentsPropsRoute
  '/chapters/conditional-rendering': typeof ChaptersConditionalRenderingRoute
  '/chapters/context': typeof ChaptersContextRoute
  '/chapters/custom-hooks': typeof ChaptersCustomHooksRoute
  '/chapters/dont-call-function-components': typeof ChaptersDontCallFunctionComponentsRoute
  '/chapters/events': typeof ChaptersEventsRoute
  '/chapters/forms': typeof ChaptersFormsRoute
  '/chapters/jsx': typeof ChaptersJsxRoute
  '/chapters/lift-content-up': typeof ChaptersLiftContentUpRoute
  '/chapters/lists-keys': typeof ChaptersListsKeysRoute
  '/chapters/memoization': typeof ChaptersMemoizationRoute
  '/chapters/move-state-down': typeof ChaptersMoveStateDownRoute
  '/chapters/react-rendering': typeof ChaptersReactRenderingRoute
  '/chapters/use-effect': typeof ChaptersUseEffectRoute
  '/chapters/use-reducer': typeof ChaptersUseReducerRoute
  '/chapters/use-ref': typeof ChaptersUseRefRoute
  '/chapters/use-state': typeof ChaptersUseStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chapters/component-design'
    | '/chapters/components-props'
    | '/chapters/conditional-rendering'
    | '/chapters/context'
    | '/chapters/custom-hooks'
    | '/chapters/dont-call-function-components'
    | '/chapters/events'
    | '/chapters/forms'
    | '/chapters/jsx'
    | '/chapters/lift-content-up'
    | '/chapters/lists-keys'
    | '/chapters/memoization'
    | '/chapters/move-state-down'
    | '/chapters/react-rendering'
    | '/chapters/use-effect'
    | '/chapters/use-reducer'
    | '/chapters/use-ref'
    | '/chapters/use-state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chapters/component-design'
    | '/chapters/components-props'
    | '/chapters/conditional-rendering'
    | '/chapters/context'
    | '/chapters/custom-hooks'
    | '/chapters/dont-call-function-components'
    | '/chapters/events'
    | '/chapters/forms'
    | '/chapters/jsx'
    | '/chapters/lift-content-up'
    | '/chapters/lists-keys'
    | '/chapters/memoization'
    | '/chapters/move-state-down'
    | '/chapters/react-rendering'
    | '/chapters/use-effect'
    | '/chapters/use-reducer'
    | '/chapters/use-ref'
    | '/chapters/use-state'
  id:
    | '__root__'
    | '/'
    | '/chapters/component-design'
    | '/chapters/components-props'
    | '/chapters/conditional-rendering'
    | '/chapters/context'
    | '/chapters/custom-hooks'
    | '/chapters/dont-call-function-components'
    | '/chapters/events'
    | '/chapters/forms'
    | '/chapters/jsx'
    | '/chapters/lift-content-up'
    | '/chapters/lists-keys'
    | '/chapters/memoization'
    | '/chapters/move-state-down'
    | '/chapters/react-rendering'
    | '/chapters/use-effect'
    | '/chapters/use-reducer'
    | '/chapters/use-ref'
    | '/chapters/use-state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChaptersComponentDesignRoute: typeof ChaptersComponentDesignRoute
  ChaptersComponentsPropsRoute: typeof ChaptersComponentsPropsRoute
  ChaptersConditionalRenderingRoute: typeof ChaptersConditionalRenderingRoute
  ChaptersContextRoute: typeof ChaptersContextRoute
  ChaptersCustomHooksRoute: typeof ChaptersCustomHooksRoute
  ChaptersDontCallFunctionComponentsRoute: typeof ChaptersDontCallFunctionComponentsRoute
  ChaptersEventsRoute: typeof ChaptersEventsRoute
  ChaptersFormsRoute: typeof ChaptersFormsRoute
  ChaptersJsxRoute: typeof ChaptersJsxRoute
  ChaptersLiftContentUpRoute: typeof ChaptersLiftContentUpRoute
  ChaptersListsKeysRoute: typeof ChaptersListsKeysRoute
  ChaptersMemoizationRoute: typeof ChaptersMemoizationRoute
  ChaptersMoveStateDownRoute: typeof ChaptersMoveStateDownRoute
  ChaptersReactRenderingRoute: typeof ChaptersReactRenderingRoute
  ChaptersUseEffectRoute: typeof ChaptersUseEffectRoute
  ChaptersUseReducerRoute: typeof ChaptersUseReducerRoute
  ChaptersUseRefRoute: typeof ChaptersUseRefRoute
  ChaptersUseStateRoute: typeof ChaptersUseStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/use-state': {
      id: '/chapters/use-state'
      path: '/chapters/use-state'
      fullPath: '/chapters/use-state'
      preLoaderRoute: typeof ChaptersUseStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/use-ref': {
      id: '/chapters/use-ref'
      path: '/chapters/use-ref'
      fullPath: '/chapters/use-ref'
      preLoaderRoute: typeof ChaptersUseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/use-reducer': {
      id: '/chapters/use-reducer'
      path: '/chapters/use-reducer'
      fullPath: '/chapters/use-reducer'
      preLoaderRoute: typeof ChaptersUseReducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/use-effect': {
      id: '/chapters/use-effect'
      path: '/chapters/use-effect'
      fullPath: '/chapters/use-effect'
      preLoaderRoute: typeof ChaptersUseEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/react-rendering': {
      id: '/chapters/react-rendering'
      path: '/chapters/react-rendering'
      fullPath: '/chapters/react-rendering'
      preLoaderRoute: typeof ChaptersReactRenderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/move-state-down': {
      id: '/chapters/move-state-down'
      path: '/chapters/move-state-down'
      fullPath: '/chapters/move-state-down'
      preLoaderRoute: typeof ChaptersMoveStateDownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/memoization': {
      id: '/chapters/memoization'
      path: '/chapters/memoization'
      fullPath: '/chapters/memoization'
      preLoaderRoute: typeof ChaptersMemoizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/lists-keys': {
      id: '/chapters/lists-keys'
      path: '/chapters/lists-keys'
      fullPath: '/chapters/lists-keys'
      preLoaderRoute: typeof ChaptersListsKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/lift-content-up': {
      id: '/chapters/lift-content-up'
      path: '/chapters/lift-content-up'
      fullPath: '/chapters/lift-content-up'
      preLoaderRoute: typeof ChaptersLiftContentUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/jsx': {
      id: '/chapters/jsx'
      path: '/chapters/jsx'
      fullPath: '/chapters/jsx'
      preLoaderRoute: typeof ChaptersJsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/forms': {
      id: '/chapters/forms'
      path: '/chapters/forms'
      fullPath: '/chapters/forms'
      preLoaderRoute: typeof ChaptersFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/events': {
      id: '/chapters/events'
      path: '/chapters/events'
      fullPath: '/chapters/events'
      preLoaderRoute: typeof ChaptersEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/dont-call-function-components': {
      id: '/chapters/dont-call-function-components'
      path: '/chapters/dont-call-function-components'
      fullPath: '/chapters/dont-call-function-components'
      preLoaderRoute: typeof ChaptersDontCallFunctionComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/custom-hooks': {
      id: '/chapters/custom-hooks'
      path: '/chapters/custom-hooks'
      fullPath: '/chapters/custom-hooks'
      preLoaderRoute: typeof ChaptersCustomHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/context': {
      id: '/chapters/context'
      path: '/chapters/context'
      fullPath: '/chapters/context'
      preLoaderRoute: typeof ChaptersContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/conditional-rendering': {
      id: '/chapters/conditional-rendering'
      path: '/chapters/conditional-rendering'
      fullPath: '/chapters/conditional-rendering'
      preLoaderRoute: typeof ChaptersConditionalRenderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/components-props': {
      id: '/chapters/components-props'
      path: '/chapters/components-props'
      fullPath: '/chapters/components-props'
      preLoaderRoute: typeof ChaptersComponentsPropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/component-design': {
      id: '/chapters/component-design'
      path: '/chapters/component-design'
      fullPath: '/chapters/component-design'
      preLoaderRoute: typeof ChaptersComponentDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChaptersComponentDesignRoute: ChaptersComponentDesignRoute,
  ChaptersComponentsPropsRoute: ChaptersComponentsPropsRoute,
  ChaptersConditionalRenderingRoute: ChaptersConditionalRenderingRoute,
  ChaptersContextRoute: ChaptersContextRoute,
  ChaptersCustomHooksRoute: ChaptersCustomHooksRoute,
  ChaptersDontCallFunctionComponentsRoute:
    ChaptersDontCallFunctionComponentsRoute,
  ChaptersEventsRoute: ChaptersEventsRoute,
  ChaptersFormsRoute: ChaptersFormsRoute,
  ChaptersJsxRoute: ChaptersJsxRoute,
  ChaptersLiftContentUpRoute: ChaptersLiftContentUpRoute,
  ChaptersListsKeysRoute: ChaptersListsKeysRoute,
  ChaptersMemoizationRoute: ChaptersMemoizationRoute,
  ChaptersMoveStateDownRoute: ChaptersMoveStateDownRoute,
  ChaptersReactRenderingRoute: ChaptersReactRenderingRoute,
  ChaptersUseEffectRoute: ChaptersUseEffectRoute,
  ChaptersUseReducerRoute: ChaptersUseReducerRoute,
  ChaptersUseRefRoute: ChaptersUseRefRoute,
  ChaptersUseStateRoute: ChaptersUseStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
