/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Chapters9RouteImport } from './routes/chapters/9'
import { Route as Chapters8RouteImport } from './routes/chapters/8'
import { Route as Chapters7RouteImport } from './routes/chapters/7'
import { Route as Chapters6RouteImport } from './routes/chapters/6'
import { Route as Chapters5RouteImport } from './routes/chapters/5'
import { Route as Chapters4RouteImport } from './routes/chapters/4'
import { Route as Chapters3RouteImport } from './routes/chapters/3'
import { Route as Chapters2RouteImport } from './routes/chapters/2'
import { Route as Chapters14RouteImport } from './routes/chapters/14'
import { Route as Chapters13RouteImport } from './routes/chapters/13'
import { Route as Chapters12RouteImport } from './routes/chapters/12'
import { Route as Chapters11RouteImport } from './routes/chapters/11'
import { Route as Chapters10RouteImport } from './routes/chapters/10'
import { Route as Chapters1RouteImport } from './routes/chapters/1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters9Route = Chapters9RouteImport.update({
  id: '/chapters/9',
  path: '/chapters/9',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters8Route = Chapters8RouteImport.update({
  id: '/chapters/8',
  path: '/chapters/8',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters7Route = Chapters7RouteImport.update({
  id: '/chapters/7',
  path: '/chapters/7',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters6Route = Chapters6RouteImport.update({
  id: '/chapters/6',
  path: '/chapters/6',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters5Route = Chapters5RouteImport.update({
  id: '/chapters/5',
  path: '/chapters/5',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters4Route = Chapters4RouteImport.update({
  id: '/chapters/4',
  path: '/chapters/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters3Route = Chapters3RouteImport.update({
  id: '/chapters/3',
  path: '/chapters/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters2Route = Chapters2RouteImport.update({
  id: '/chapters/2',
  path: '/chapters/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters14Route = Chapters14RouteImport.update({
  id: '/chapters/14',
  path: '/chapters/14',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters13Route = Chapters13RouteImport.update({
  id: '/chapters/13',
  path: '/chapters/13',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters12Route = Chapters12RouteImport.update({
  id: '/chapters/12',
  path: '/chapters/12',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters11Route = Chapters11RouteImport.update({
  id: '/chapters/11',
  path: '/chapters/11',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters10Route = Chapters10RouteImport.update({
  id: '/chapters/10',
  path: '/chapters/10',
  getParentRoute: () => rootRouteImport,
} as any)
const Chapters1Route = Chapters1RouteImport.update({
  id: '/chapters/1',
  path: '/chapters/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chapters/1': typeof Chapters1Route
  '/chapters/10': typeof Chapters10Route
  '/chapters/11': typeof Chapters11Route
  '/chapters/12': typeof Chapters12Route
  '/chapters/13': typeof Chapters13Route
  '/chapters/14': typeof Chapters14Route
  '/chapters/2': typeof Chapters2Route
  '/chapters/3': typeof Chapters3Route
  '/chapters/4': typeof Chapters4Route
  '/chapters/5': typeof Chapters5Route
  '/chapters/6': typeof Chapters6Route
  '/chapters/7': typeof Chapters7Route
  '/chapters/8': typeof Chapters8Route
  '/chapters/9': typeof Chapters9Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chapters/1': typeof Chapters1Route
  '/chapters/10': typeof Chapters10Route
  '/chapters/11': typeof Chapters11Route
  '/chapters/12': typeof Chapters12Route
  '/chapters/13': typeof Chapters13Route
  '/chapters/14': typeof Chapters14Route
  '/chapters/2': typeof Chapters2Route
  '/chapters/3': typeof Chapters3Route
  '/chapters/4': typeof Chapters4Route
  '/chapters/5': typeof Chapters5Route
  '/chapters/6': typeof Chapters6Route
  '/chapters/7': typeof Chapters7Route
  '/chapters/8': typeof Chapters8Route
  '/chapters/9': typeof Chapters9Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chapters/1': typeof Chapters1Route
  '/chapters/10': typeof Chapters10Route
  '/chapters/11': typeof Chapters11Route
  '/chapters/12': typeof Chapters12Route
  '/chapters/13': typeof Chapters13Route
  '/chapters/14': typeof Chapters14Route
  '/chapters/2': typeof Chapters2Route
  '/chapters/3': typeof Chapters3Route
  '/chapters/4': typeof Chapters4Route
  '/chapters/5': typeof Chapters5Route
  '/chapters/6': typeof Chapters6Route
  '/chapters/7': typeof Chapters7Route
  '/chapters/8': typeof Chapters8Route
  '/chapters/9': typeof Chapters9Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chapters/1'
    | '/chapters/10'
    | '/chapters/11'
    | '/chapters/12'
    | '/chapters/13'
    | '/chapters/14'
    | '/chapters/2'
    | '/chapters/3'
    | '/chapters/4'
    | '/chapters/5'
    | '/chapters/6'
    | '/chapters/7'
    | '/chapters/8'
    | '/chapters/9'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chapters/1'
    | '/chapters/10'
    | '/chapters/11'
    | '/chapters/12'
    | '/chapters/13'
    | '/chapters/14'
    | '/chapters/2'
    | '/chapters/3'
    | '/chapters/4'
    | '/chapters/5'
    | '/chapters/6'
    | '/chapters/7'
    | '/chapters/8'
    | '/chapters/9'
  id:
    | '__root__'
    | '/'
    | '/chapters/1'
    | '/chapters/10'
    | '/chapters/11'
    | '/chapters/12'
    | '/chapters/13'
    | '/chapters/14'
    | '/chapters/2'
    | '/chapters/3'
    | '/chapters/4'
    | '/chapters/5'
    | '/chapters/6'
    | '/chapters/7'
    | '/chapters/8'
    | '/chapters/9'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Chapters1Route: typeof Chapters1Route
  Chapters10Route: typeof Chapters10Route
  Chapters11Route: typeof Chapters11Route
  Chapters12Route: typeof Chapters12Route
  Chapters13Route: typeof Chapters13Route
  Chapters14Route: typeof Chapters14Route
  Chapters2Route: typeof Chapters2Route
  Chapters3Route: typeof Chapters3Route
  Chapters4Route: typeof Chapters4Route
  Chapters5Route: typeof Chapters5Route
  Chapters6Route: typeof Chapters6Route
  Chapters7Route: typeof Chapters7Route
  Chapters8Route: typeof Chapters8Route
  Chapters9Route: typeof Chapters9Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/9': {
      id: '/chapters/9'
      path: '/chapters/9'
      fullPath: '/chapters/9'
      preLoaderRoute: typeof Chapters9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/8': {
      id: '/chapters/8'
      path: '/chapters/8'
      fullPath: '/chapters/8'
      preLoaderRoute: typeof Chapters8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/7': {
      id: '/chapters/7'
      path: '/chapters/7'
      fullPath: '/chapters/7'
      preLoaderRoute: typeof Chapters7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/6': {
      id: '/chapters/6'
      path: '/chapters/6'
      fullPath: '/chapters/6'
      preLoaderRoute: typeof Chapters6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/5': {
      id: '/chapters/5'
      path: '/chapters/5'
      fullPath: '/chapters/5'
      preLoaderRoute: typeof Chapters5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/4': {
      id: '/chapters/4'
      path: '/chapters/4'
      fullPath: '/chapters/4'
      preLoaderRoute: typeof Chapters4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/3': {
      id: '/chapters/3'
      path: '/chapters/3'
      fullPath: '/chapters/3'
      preLoaderRoute: typeof Chapters3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/2': {
      id: '/chapters/2'
      path: '/chapters/2'
      fullPath: '/chapters/2'
      preLoaderRoute: typeof Chapters2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/14': {
      id: '/chapters/14'
      path: '/chapters/14'
      fullPath: '/chapters/14'
      preLoaderRoute: typeof Chapters14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/13': {
      id: '/chapters/13'
      path: '/chapters/13'
      fullPath: '/chapters/13'
      preLoaderRoute: typeof Chapters13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/12': {
      id: '/chapters/12'
      path: '/chapters/12'
      fullPath: '/chapters/12'
      preLoaderRoute: typeof Chapters12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/11': {
      id: '/chapters/11'
      path: '/chapters/11'
      fullPath: '/chapters/11'
      preLoaderRoute: typeof Chapters11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/10': {
      id: '/chapters/10'
      path: '/chapters/10'
      fullPath: '/chapters/10'
      preLoaderRoute: typeof Chapters10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/1': {
      id: '/chapters/1'
      path: '/chapters/1'
      fullPath: '/chapters/1'
      preLoaderRoute: typeof Chapters1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Chapters1Route: Chapters1Route,
  Chapters10Route: Chapters10Route,
  Chapters11Route: Chapters11Route,
  Chapters12Route: Chapters12Route,
  Chapters13Route: Chapters13Route,
  Chapters14Route: Chapters14Route,
  Chapters2Route: Chapters2Route,
  Chapters3Route: Chapters3Route,
  Chapters4Route: Chapters4Route,
  Chapters5Route: Chapters5Route,
  Chapters6Route: Chapters6Route,
  Chapters7Route: Chapters7Route,
  Chapters8Route: Chapters8Route,
  Chapters9Route: Chapters9Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
